# Build matrix pipeline:
# 
# This pipeline checks that pre-releases and the main branch
# compile in a wide variety of build environments. This pipeline
# is intended to be a rigorous check of GCHP's build.


# This pipeline triggers on tagged pre-releases (alpha and beta 
# versions, as well as release candidates). Commits to the main 
# branch also trigger this pipeline.
trigger:
  branches:
    include:
      - main
  tags:
    include:        # Semantic versioning 2.0.0 examples:
      - '*-alpha*'  # 12.7.1-alpha.3
      - '*-beta*'   # 12.7.0-beta.1
      - '*-rc*'     # 12.7.0-rc.1
pr: none


# Basic agent set up
pool:
  vmImage: 'ubuntu-latest'


# Define the "matrix" of build images to try building GCHP in
strategy:
  matrix:
    ubuntu_basic:
      containerImage: geoschem/buildmatrix:esmf-ubuntu
    gcc8:
      containerImage: geoschem/buildmatrix:esmf-gcc8
    gcc9:
      containerImage: geoschem/buildmatrix:esmf-gcc9
    gcc10:
      containerImage: geoschem/buildmatrix:esmf-gcc10
    openmpi401:
      containerImage: geoschem/buildmatrix:esmf_slim-openmpi4.0.1-ubuntu
    openmpi304:
      containerImage: geoschem/buildmatrix:esmf_slim-openmpi3.0.4-ubuntu
    openmpi314:
      containerImage: geoschem/buildmatrix:esmf_slim-openmpi3.1.4-ubuntu
container: $[ variables['containerImage'] ]


# Try building GCHP (this is run for each "matrix" entry above)
steps:
- checkout: self
  submodules: recursive
- script: |
    . /opt/spack/share/spack/setup-env.sh
    export CC=gcc
    export CXX=g++
    export FC=gfortran
    set -x
    spack load cmake
    spack load m4
    spack load mpi
    spack load hdf5 
    spack load netcdf-c
    spack load netcdf-fortran
    spack load esmf
    mkdir build
    cd build
    cmake $(Build.Repository.LocalPath) -DCMAKE_COLOR_MAKEFILE=FALSE -DRUNDIR=$(Build.Repository.LocalPath)/.ci-pipelines/MinimumStandaloneTransportTracer
    make -j install
  displayName: 'Building GCHP'
# - script: |
#     . /opt/spack/share/spack/setup-env.sh
#     spack load cmake
#     spack load m4
#     spack load mpi
#     spack load hdf5 
#     spack load netcdf-c
#     spack load netcdf-fortran
#     spack load esmf
#     cd $(Build.Repository.LocalPath)/.ci-pipelines/MinimumStandaloneTransportTracer
#     export OMPI_MCA_btl_vader_single_copy_mechanism=none
#     mpirun --oversubscribe -np 6 ./gchp
#     test -f OutputDir/GCHP.SpeciesConc.*.nc4
#   displayName: 'Run GCHP'
