# Quick test pipeline:
# 
# This pipeline checks that commits and pull requests don't
# introduce compiler errors. This is meant to be a quick and simple
# check that runs frequently.

# This pipeline triggers on commits to development and bug-fix
# branches. Commits to the main branch do not trigger this pipeline
# because those are tested by the build matrix. Commits to feature
# branches do not trigger this pipeline, but open pull requests and
# commits to pull requests do.
trigger:
  branches:
    include:
      - dev*
      - bugfix*
pr:
  branches:
    include:
      - '*'


# Basic agent and container set up
pool:
  vmImage: 'ubuntu-latest'
container: liambindle/penelope:2019.12-centos7-openmpi3.1.4-esmf8.0.0


# Pipeline definition for building GCHP
steps:
- checkout: self
  submodules: true
- script: |
    source /init.rc
    module load gcc/8
    export CC=gcc
    export CXX=g++
    export FC=gfortran
    spack load openmpi
    spack load hdf5 
    spack load netcdf-c
    spack load netcdf-fortran
    spack load esmf
    git -c $(Build.Repository.LocalPath) submodule update --init --recursive
    mkdir build
    cd build
    cmake -DCMAKE_COLOR_MAKEFILE=FALSE $(Build.Repository.LocalPath)
    make -j geos
  displayName: 'Building GCHP'
