# Quick test pipeline:
# 
# This pipeline checks that commits and pull requests don't
# introduce compiler and run-time errors. This is meant to be a
# quick and simple check that runs frequently.

# This pipeline is currently not executed for any branches pending
# additional work on the quick test run directory setup. However,
# this pipeline will eventually be triggered on commits to development
# and bug-fix branches. Commits to the main branch will not trigger
# this pipeline because those are tested by the build matrix. Commits
# to feature branches will not trigger this pipeline, but open pull
# requests and commits to pull requests will.
trigger:
  branches:
    exclude:
      - '*'
pr:
  branches:
    exclude:
      - '*'


# Basic agent and container set up
pool:
  vmImage: 'ubuntu-latest'
container: liambindle/penelope:2019.12-centos7-openmpi3.1.4-esmf8.0.0

# Pipeline definition for build and run
steps:
- checkout: self
  submodules: recursive
- script: |
    source /init.rc
    module load gcc/8
    export CC=gcc
    export CXX=g++
    export FC=gfortran
    spack load openmpi
    spack load hdf5 
    spack load netcdf-c
    spack load netcdf-fortran
    spack load esmf
    mkdir build
    cd build
    cmake $(Build.Repository.LocalPath) -DCMAKE_COLOR_MAKEFILE=FALSE -DRUNDIR=$(Build.Repository.LocalPath)/.ci-pipelines/MinimumStandaloneTransportTracer
    make -j install
  displayName: 'Build GCHP'
- script: |
    source /init.rc
    module load gcc/8
    spack load openmpi
    spack load hdf5 
    spack load netcdf-c
    spack load netcdf-fortran
    spack load esmf
    cd $(Build.Repository.LocalPath)/.ci-pipelines/MinimumStandaloneTransportTracer
    export OMPI_MCA_btl_vader_single_copy_mechanism=none
    mpirun --oversubscribe -np 6 ./gchp
    test -f OutputDir/GCHP.SpeciesConc.*.nc4
  displayName: 'Run GCHP'