# Release pipeline:
# 
# This pipeline performs deployment actions upon a GEOS-Chem release.
# Currently, the only deployment action is to build and push a docker 
# container with GCHP for the newly released version.

# This pipeline is triggered by tagged versions excluding 
# pre-releases.
name: spack_deployment
on:
  push:
    branches:
    - feature/spack-pipeline
jobs:
  spack_deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
          echo ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Build
        run: |
          docker build -f ./.github/workflows/spack-deployment/spack-deployment.dockerfile --build-arg gh-access-token=${{ secrets.GITHUB_TOKEN }} ./.github/workflows/spack-deployment/
