# Release pipeline:
# 
# This pipeline performs the deployment of a new gchp spack
# package upon the release of a new version

# This pipeline is triggered by tagged versions excluding 
# pre-releases.
name: spack_deployment
on:
  push:
    tags:
      - '*' 
    tags-ignore:
      - '*-alpha*'
      - '*-beta*'
      - '*-rc*'
jobs:
  spack_deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}
      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      - name: Build
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          docker build -f ./.github/workflows/spack-deployment/spack-deployment.dockerfile --build-arg gh_access_token=${{ secrets.GH_ACCESS_TOKEN }} --build-arg version_tag=$RELEASE_VERSION ./.github/workflows/spack-deployment/
